### ISSUE TITLE
Add get number of client connections

### ISSUE THREAD

**Issue by jakekgrog** [jakekgrog/GhostDB#24]
For the GhostDB CLI we need a way of counting the number of active connections to each node in a cluster.

**Comment by jakekgrog** [comment]
---
Name: Get client connections
About: New endpoint to get number of active connections.
Labels: Feature
---

## Summary

Provide users a way of fetching information about the number of active connection to a node.

### Basic example

- This will include a new endpoint to the server: `/getActiveConnections`

- This will include a new method in our SDKs
  - `cache.getActiveConnections("127.0.0.1")`

### Motivation

We want to add this feature as it will enrich our SDKs and primarily our CLI. With this feature, users will be able to fetch information about the number of active connections to a node in their cluster

**Comment by Adm28** [comment]
@jakekgrog I would like to give this a shot

**Comment by jakekgrog** [comment]
@Adm28 Go for it! It wont include changes to the store. It will only include changes to the server.

**Comment by avinassh** [comment]
I think this issue can be closed since it is merged with #33
